version: '3'
services:
  es-pract6:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data6:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  heartbeat-pract6:
    user: root
    image: docker.elastic.co/beats/heartbeat-oss:7.2.0
    container_name: heartbeat-pract6
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
  kibana-pract6:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    environment:
      ELASTICSEARCH_URL: http://es-pract6:9200
    ports:
      - 5601:5601
volumes:
  es-data6:
    driver: local


