version: '3'
services:
  es-pract5:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: es-pract5
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data5:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  filebeat-pract5:
    user: root
    image: docker.elastic.co/beats/filebeat-oss:7.2.0
    container_name: filebeat-pract5
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers
  kibana-pract5:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    environment:
      ELASTICSEARCH_URL: http://es-pract5:9200
    ports:
      - 5601:5601
volumes:
  es-data5:
    driver: local


