version: '3'
services:
  es-pract9:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data9:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  logstash-pract9:
    user: root
    image: docker.elastic.co/logstash/logstash-oss:7.2.0
    container_name: logstash-pract9
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
  filebeat-pract9:
    user: root
    image: docker.elastic.co/beats/filebeat-oss:7.2.0
    container_name: filebeat-pract9
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data/:/var/log/pratc9/
  kibana-pract9:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    environment:
     ELASTICSEARCH_URL: http://es-pract9:9200
    ports:
      - 5601:5601
volumes:
  es-data9:
    driver: local


