version: '3'
services:
  es-pract8:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data8:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    #Healthcheck to confirm availability of ES. Other containers wait on this.
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
  filebeat-pract8:
    user: root
    image: docker.elastic.co/beats/filebeat-oss:7.2.0
    container_name: filebeat-pract5
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers
      - ./logs/nginx/:/var/log/nginx/
  metricbeat-pract8:
    user: root
    image: docker.elastic.co/beats/metricbeat-oss:7.2.0
    container_name: metricbeat-pract8
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
  heartbeat-pract8:
    user: root
    image: docker.elastic.co/beats/heartbeat-oss:7.2.0
    container_name: heartbeat-pract8
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
  kibana-pract8:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    environment:
      ELASTICSEARCH_URL: http://es-pract8:9200
    ports:
      - 5601:5601
  nginx-pract8:
    container_name: nginx-pract8
    hostname: nginx
    build: ./nginx
    #Expose port 80 to allow users to hit content and generate data for filebeat and packetbeat
    ports: ['8080:80']
    command: nginx -g 'daemon off;'
    volumes:
      #Logs are mounted to a relative path. These are also accessed by Filebeat and consumed by the Nginx module
      - ./logs/nginx/:/var/log/nginx/
volumes:
  es-data8:
    driver: local


